SET AUTODDL ON;

DROP view VIEW_TIPODOCUME;
DROP table DF_TIPODOCIVA;
COMMIT;

CREATE TABLE DF_TIPODOCIVA
(
  CODICE varchar(5) NOT NULL,
  DESCRI varchar(255),
  CONSTRAINT DF_TIPODOCIVA PRIMARY KEY (CODICE)
);
COMMIT;

UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD00', 'Documento escluso da fatturazione elettronica');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD01', 'fattura');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD02', 'acconto/anticipo su fattura');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD03', 'acconto/anticipo su parcella');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD04', 'nota di credito');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD05', 'nota di debito');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD06', 'parcella');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD16', 'integrazione fattura reverse charge interno');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD17', 'integrazione/autofattura per acquisto servizi dall''estero');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD18', 'integrazione per acquisto di beni intracomunitari');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD19', 'integrazione/autofattura per acquisto di beni ex art.17 c.2 DPR 633/72');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD20', 'autofattura per regolarizzazione e integrazione delle fatture (ex art.6 c.8 d.lgs. 471/97  o  art.46 c.5 D.L. 331/93)');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD21', 'autofattura per splafonamento');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD22', 'estrazione beni da Deposito IVA');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD23', 'estrazione beni da Deposito IVA con versamento dell''IVA');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD24', 'fattura differita di cui all''art. 21, comma 4, lett. a)');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD25', 'fattura differita di cui all''art. 21, comma 4, terzo periodo lett. b)');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD26', 'cessione di beni ammortizzabili e per passaggi interni (ex art.36 DPR 633/72)');
UPDATE OR INSERT INTO DF_TIPODOCIVA (CODICE, DESCRI) VALUES ('TD27', 'fattura per autoconsumo o per cessioni gratuite senza rivalsa');

CREATE VIEW VIEW_TIPODOCUME (CODICE, DESCRI, REGIVA, DESCREGIVA, TIPOREGIVA, TIPODOC, DESCTIPODOC)
AS      
SELECT DC.CODICE, DC.DESCRI, DC.REGIVA, RG.DESCRI, RG.TIPORG, DC.TIPODOC_DF, TD.DESCRI
FROM TAB_TIPODOCUME DC
INNER JOIN TAB_REGISTRIIVA RG ON DC.REGIVA = RG.CODICE
INNER JOIN DF_TIPODOCIVA TD ON DC.TIPODOC_DF = TD.CODICE
ORDER BY DC.CODICE;

UPDATE TAB_TIPODOCUME SET 
CODICE = 'RIF', 
DESCRI = 'RICEVUTA FISCALE', 
REGIVA = '001', 
TIPODOC_DF = 'TD06'
WHERE CODICE = 'RIF';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'RIX', 
DESCRI = 'COMPENSO ASUR', 
REGIVA = '002', 
TIPODOC_DF = 'TD00'
WHERE CODICE = 'RIX';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'AFT', 
DESCRI = 'AUROFATTURA', 
REGIVA = '004', 
TIPODOC_DF = 'TD20'
WHERE CODICE = 'AFT';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'FTV', 
DESCRI = 'FATT VENDITA', 
REGIVA = '003', 
TIPODOC_DF = 'TD01'
WHERE CODICE = 'FTV';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'FAC', 
DESCRI = 'FATT ACQUISTO', 
REGIVA = '005', 
TIPODOC_DF = 'TD00'
WHERE CODICE = 'FAC';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'FVR', 
DESCRI = 'FATT VENDITA RIEPILOG', 
REGIVA = '003', 
TIPODOC_DF = 'TD01'
WHERE CODICE = 'FVR';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'FAR', 
DESCRI = 'FATT ACQUISTO RIEPILOG', 
REGIVA = '005', 
TIPODOC_DF = 'TD00'
WHERE CODICE = 'FAR';
UPDATE TAB_TIPODOCUME SET 
CODICE = 'FT1', 
DESCRI = 'FATT VENDITA ELETT', 
REGIVA = '006', 
TIPODOC_DF = 'TD01'
WHERE CODICE = 'FT1';
COMMIT;
