SET AUTODDL ON;
SET TERM ^ ;
ALTER PROCEDURE DOCUMENTI_PAGATI (
    I$CODEAZI char(3),
    I$REGIVA char(3),
    I$DATA1 date,
    I$DATA2 date )
RETURNS (
    PROGDOC integer,
    CODEAZI char(3),
    REGIVA char(3),
    TIPODOC char(3),
    DESCDOC varchar(20),
    NUMEREG integer,
    DATAREG date,
    NUMEDOC varchar(20),
    DATADOC date,
    CODEANA varchar(10),
    DESCANA varchar(100),
    IMPORTO numeric(9,2),
    DATAPAG date )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

DROP view VIEW_MOVCASSA;
DROP TABLE TAB_MODOPAGAM;
commit;

ALTER TABLE MOVCASSA ALTER TIPOPAG TYPE Varchar(5);

CREATE TABLE TAB_MODOPAGAM
(
  CODICE varchar(5) NOT NULL,
  DESCRI varchar(64),
  CONSTRAINT PK_TAB002 PRIMARY KEY (CODICE)
);
commit;

INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP01', 'contanti');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP02', 'assegno');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP03', 'assegno circolare');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP04', 'contanti presso Tesoreria');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP05', 'bonifico');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP06', 'vaglia cambiario');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP07', 'bollettino bancario');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP08', 'carta di pagamento');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP09', 'RID');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP10', 'RID utenze');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP11', 'RID veloce');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP12', 'RIBA');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP13', 'MAV');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP14', 'quietanza erario');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP15', 'giroconto su conti di contabilità speciale');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP16', 'domiciliazione bancaria');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP17', 'domiciliazione postale');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP18', 'bollettino di c/c postale');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP19', 'SEPA Direct Debit');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP20', 'SEPA Direct Debit CORE');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP21', 'SEPA Direct Debit B2B');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP22', 'Trattenuta su somme già riscosse');
INSERT INTO TAB_MODOPAGAM (CODICE, DESCRI) VALUES ('MP23', 'PagoPA');

UPDATE MOVCASSA SET TIPOPAG='MP01';
commit;

CREATE VIEW VIEW_MOVCASSA (PROGMVM, CODEAZI, REGCAS, TIPOMVM, DESCMVM, DATAREG, DATACOMP, CODEANA, DESCANA, PROGDOC, TIPODOC, NUMEREGDOC, DATAREGDOC, NUMEDOC, DATADOC, TIPOPAG, DESCPAG, IMPORTO)
AS         
SELECT r.PROGMVM, r.CODEAZI, MC.REGCAS, r.TIPOMVM, MC.DESCRI as DESCMVM, 
r.DATAREG, r.DATACOMP, r.CODEANA, COALESCE(AN.DESCANA, ''), r.PROGDOC, 
coalesce(DOC.TIPODOC,''), coalesce(DOC.NUMEREG,0), 
coalesce(DOC.DATAREG,'01.01.1900'), coalesce(DOC.NUMEDOC,''), 
coalesce(DOC.DATADOC,'01.01.1900'), r.TIPOPAG, MP.DESCRI as DESCPAG, r.IMPORTO
FROM MOVCASSA r 
INNER JOIN TAB_TIPOMOVCAS MC ON r.TIPOMVM=MC.CODICE
INNER JOIN TAB_MODOPAGAM  MP ON r.TIPOPAG=MP.CODICE
LEFT JOIN DOCUMENTI DOC ON R.PROGDOC = DOC.PROGDOC
LEFT JOIN ANAGRA AN ON r.CODEANA = AN.CODEANA;
commit;

SET TERM ^ ;
ALTER PROCEDURE DOCUMENTI_PAGATI (
    I$CODEAZI char(3),
    I$REGIVA char(3),
    I$DATA1 date,
    I$DATA2 date )
RETURNS (
    PROGDOC integer,
    CODEAZI char(3),
    REGIVA char(3),
    TIPODOC char(3),
    DESCDOC varchar(20),
    NUMEREG integer,
    DATAREG date,
    NUMEDOC varchar(20),
    DATADOC date,
    CODEANA varchar(10),
    DESCANA varchar(100),
    IMPORTO numeric(9,2),
    DATAPAG date )
AS
BEGIN
  FOR SELECT MC.PROGDOC,MC.CODEAZI,TD.REGIVA,MC.TIPODOC,TD.DESCRI,MC.NUMEREGDOC, 
  MC.DATAREGDOC,MC.NUMEDOC,MC.DATADOC,MC.CODEANA,MC.DESCANA,MC.IMPORTO,MC.DATACOMP
    FROM VIEW_MOVCASSA MC
    INNER JOIN TAB_TIPODOCUME TD ON MC.TIPODOC=TD.CODICE
    WHERE MC.CODEAZI=:I$CODEAZI AND TD.REGIVA=:I$REGIVA 
    AND MC.DATAREGDOC < :I$DATA1 AND MC.DATACOMP BETWEEN :I$DATA1 AND :I$DATA2
    INTO :PROGDOC,:CODEAZI,:REGIVA,:TIPODOC,:DESCDOC,:NUMEREG,:DATAREG,
    :NUMEDOC,:DATADOC,:CODEANA,:DESCANA,:IMPORTO,:DATAPAG
    DO
    BEGIN
    SUSPEND;
    END
END^
SET TERM ; ^
